const table_html = '<table class="veiw-memes__memes-table" id="memes-table-or-list"><caption class="veiw-memes__table-name">Memes</caption><tr class="veiw-memes__table-line veiw-memes__table-line_red-line"><th class="veiw-memes__table-mem"><a class="veiw-memes__table-mem-reference" href="memes/1.html"><img class="veiw-memes__table-mem-image" src="image/memes/1433439830_987359008.jpg" alt=""></a></th><th class="veiw-memes__table-mem"><a class="veiw-memes__table-mem-reference" href="memes/2.html"><img class="veiw-memes__table-mem-image" src="image/memes/6d85f5807f50984a6fee548d2a58f1746364f9b7_full.jpg" alt=""></a></th><th class="veiw-memes__table-mem"><a class="veiw-memes__table-mem-reference" href="memes/3.html"><img class="veiw-memes__table-mem-image" src="image/memes/x1807884-184419071.png" alt=""></a></th><th class="veiw-memes__table-mem"><a class="veiw-memes__table-mem-reference" href="memes/4.html"><img class="veiw-memes__table-mem-image" src="image/memes/x2043832-1037640997.png" alt=""></a></th></tr><tr class="veiw-memes__table-line veiw-memes__table-line_blue-line"><th class="veiw-memes__table-mem"><a class="veiw-memes__table-mem-reference" href="memes/5.html"><img class="veiw-memes__table-mem-image" src="image/memes/x289168-1955492593.png" alt=""></a></th><th class="veiw-memes__table-mem"><a class="veiw-memes__table-mem-reference" href="memes/6.html"><img class="veiw-memes__table-mem-image" src="image/memes/x3129690-1238090283.png" alt=""></a></th><th class="veiw-memes__table-mem"><a class="veiw-memes__table-mem-reference" href="memes/7.html"><img class="veiw-memes__table-mem-image" src="image/memes/x3976986-688524785.png" alt=""></a></th><th class="veiw-memes__table-mem"><a class="veiw-memes__table-mem-reference" href="memes/8.html"><img class="veiw-memes__table-mem-image" src="image/memes/xxh.png" alt=""></a></th></tr></table>';

const list_html = '<ol class="veiw-memes__memes-list" id="memes-table-or-list">            <caption class="veiw-memes_list-name">Memes</caption>                        <li class="veiw-memes__list-mem veiw-memes__list-mem_red">                <a class="veiw-memes__mem-reference" href="memes/1.html">                    <img class="veiw-memes__mem-image" src="image/memes/1433439830_987359008.jpg" alt="">                </a>            </li>            <li class="veiw-memes__list-mem veiw-memes__list-mem_blue">                <a class="veiw-memes__mem-reference" href="memes/2.html">                    <img class="veiw-memes__mem-image" src="image/memes/6d85f5807f50984a6fee548d2a58f1746364f9b7_full.jpg" alt="">                </a>            </li>            <li class="veiw-memes__list-mem veiw-memes__list-mem_green">                <a class="veiw-memes__mem-reference" href="memes/3.html">                    <img class="veiw-memes__mem-image" src="image/memes/x1807884-184419071.png" alt="">                </a>            </li>            <li class="veiw-memes__list-mem veiw-memes__list-mem_yellow">                <a class="veiw-memes__mem-reference" href="memes/4.html">                    <img class="veiw-memes__mem-image" src="image/memes/x2043832-1037640997.png" alt="">                </a>            </li>            <li class="veiw-memes__list-mem veiw-memes__list-mem_violet">                <a class="veiw-memes__mem-reference" href="memes/5.html">                    <img class="veiw-memes__mem-image" src="image/memes/x289168-1955492593.png" alt="">                </a>            </li>            <li class="veiw-memes__list-mem veiw-memes__list-mem_black">                <a class="veiw-memes__mem-reference" href="memes/6.html">                    <img class="veiw-memes__mem-image" src="image/memes/x3129690-1238090283.png" alt="">                </a>            </li>            <li class="veiw-memes__list-mem veiw-memes__list-mem_white">                <a class="veiw-memes__mem-reference" href="memes/7.html">                    <img class="veiw-memes__mem-image" src="image/memes/x3976986-688524785.png" alt="">                </a>            </li>            <li class="veiw-memes__list-mem veiw-memes__list-mem_orange">                <a class="veiw-memes__mem-reference" href="memes/8.html">                    <img class="veiw-memes__mem-image" src="image/memes/xxh.png" alt="">                </a>            </li>        </ol>';

document.getElementById("settings-veiw-memes-block").onclick = function() {
    let is_table = document.getElementById("memes-table-or-list").nodeName === "TABLE";
    document.getElementById("memes-table-or-list").remove();

    if (is_table) {
        let div = document.getElementById("veiw-memes-block");
        div.insertAdjacentHTML("afterbegin", list_html)
    } else {
        let div = document.getElementById("veiw-memes-block");
        div.insertAdjacentHTML("afterbegin", table_html);
    }
}
