@Homework10_HostAddress = http://localhost:5127

POST {{Homework10_HostAddress}}/comments/
Accept: application/json

{
  "name" = "new_commnet"
  "postId" = 100
  "email" = "test"
  "body" = "testy"
}

###
